//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from Scaffolding.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;

#nullable disable

namespace IMDBAssignment.Models.DAL
{
    public partial class Actor
    {
        /// <summary>
        /// Constructor.
        /// </summary>
        public Actor()
        {
            MovieActors = new HashSet<MovieActor>();
        }

        /// <summary>
        /// Gets or sets for Id
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets for ActorName
        /// </summary>
        public string ActorName { get; set; }

        /// <summary>
        /// Gets or sets for DateBirth
        /// </summary>
        public DateTime DateBirth { get; set; }

        /// <summary>
        /// Gets or sets for Bio
        /// </summary>
        public string Bio { get; set; }

        /// <summary>
        /// Gets or sets for Gender
        /// </summary>
        public string Gender { get; set; }

        /// <summary> Read-Only Navigation Property to the Movie Actor. </summary>
        public virtual ICollection<MovieActor> MovieActors { get; private set; }
    }
}
