//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from Scaffolding.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

#nullable disable

namespace IMDBAssignment.Models.DAL
{
    public partial class Movie
    {
        /// <summary>
        /// Constructor.
        /// </summary>
        public Movie()
        {
            MovieActors = new HashSet<MovieActor>();
        }

        /// <summary>
        /// Gets or sets for Id.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets for Movie Name.
        /// </summary>
        public string MovieName { get; set; }

        /// <summary>
        /// Gets or sets for Date Release.
        /// </summary>
        public DateTime DateRelease { get; set; }

        /// <summary>
        /// Gets or sets for Producer Id.
        /// </summary>
        public int ProducerId { get; set; }

        /// <summary>
        /// Gets or sets for Description.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets for Poster Path.
        /// </summary>
        public string PosterPath { get; set; }

        /// <summary> Read-Only Navigation Property to the Producer. </summary>
        public virtual Producer Producer { get; private set; }

        /// <summary> Read-Only Navigation Property to the Movie Actor. </summary>
        public virtual ICollection<MovieActor> MovieActors { get; private set; }
    }
}
