//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from Scaffolding.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

#nullable disable

namespace IMDBAssignment.Models.DAL
{
    public partial class Producer
    {
        /// <summary>
        /// Constructor.
        /// </summary>
        public Producer()
        {
            Movies = new HashSet<Movie>();
        }


        /// <summary>
        /// Gets or sets for Id
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets for Producer Name
        /// </summary>
        public string ProducerName { get; set; }

        /// <summary>
        /// Gets or sets for Date Birth.
        /// </summary>
        public DateTime DateBirth { get; set; }

        /// <summary>
        /// Gets or sets for Company Name
        /// </summary>
        public string CompanyName { get; set; }

        /// <summary>
        /// Gets or sets for Bio
        /// </summary>
        public string Bio { get; set; }

        /// <summary>
        /// Gets or sets for Gender
        /// </summary>
        public string Gender { get; set; }

        /// <summary> Read-Only Navigation Property to the Movie. </summary>
        public virtual ICollection<Movie> Movies { get; private set; }
    }
}
